version: 2

formats:
  - htmlzip

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - rsync
  jobs:
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/mathvizanimator/html/
      - ls docs/mathvizanimator/html
      - ls $READTHEDOCS_OUTPUT/html/mathvizanimator/html
     # - rsync --recursive -av docs/mathvizanimator/html/ $READTHEDOCS_OUTPUT/html/mathvizanimator/html --exclude='*.html' --exclude='*.css' --exclude='*.js' --exclude='*.rst' 
      - find docs/mathvizanimator/html/ \( -name "*.png" -or -name "*.svg" \) -exec cp -v {} $READTHEDOCS_OUTPUT/html/mathvizanimator/html  \;
      - ls $READTHEDOCS_OUTPUT
      - ls $READTHEDOCS_OUTPUT/html
      - ls $READTHEDOCS_OUTPUT/html/mathvizanimator
      - ls $READTHEDOCS_OUTPUT/html/mathvizanimator/html

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

submodules:
  include:
    - docs/doxygen-awesome-css
  recursive: true